In [67]:
import pandas as pd

In [68]:
# load data
path = "~/my_project_dir/selenium_webScraper/"
data = pd.read_csv(path+"centris_montreal_complete.csv", index_col=0)
print(data.shape)
data.head()

(5732, 100)

,title,address,price,lat,long,Restaurants,Shopping,Vibrant,Cycling friendly,Car friendly,...,Residential unit,bedrooms in basement,Zoning,Parking (excluded from the price),bedroom in basement,< 15 years (%),15 to 24 years (%),25 to 44 years (%),45 to 64 years (%),> 65 years (%)
0,Condo for sale,"5050, Rue Bannantyne, apt. 203, Montréal (Verd...","$409,000",45.456079,-73.575949,7.0,8.0,5.0,9.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Condo for sale,"201, Chemin de la Pointe-Sud, apt. 216, Montré...","$680,000",45.449347,-73.553327,3.0,3.0,1.0,7.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Condo for sale,"8800, Rue Verville, apt. 101, Montréal (Ahunts...","$283,000",45.536589,-73.646590,8.0,10.0,5.0,3.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Condo for sale,"185, Rue du Séminaire, apt. 605, Montréal (Le ...","$339,000",45.490915,-73.560779,10.0,10.0,9.0,9.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Condo for sale,"7075, Rue Bombardier, apt. 108, Montréal (Anjou)","$177,800",45.606186,-73.588353,6.0,7.0,3.0,4.0,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [69]:
data.describe()

,lat,long,Restaurants,Shopping,Vibrant,Cycling friendly,Car friendly,Historic,Quiet,Elementary Schools,...,powder room,powder rooms,room,bedrooms in basement,bedroom in basement,< 15 years (%),15 to 24 years (%),25 to 44 years (%),45 to 64 years (%),> 65 years (%)
count,5732.000000,5732.000000,5724.000000,5726.000000,5724.000000,5723.000000,5721.000000,5714.000000,5716.000000,5728.000000,...,1137.0,84.000000,32.0,46.000000,31.0,1.0,1.0,1.0,1.0,1.0
mean,45.517092,-73.608633,7.851153,8.037897,6.098532,6.702254,6.457438,4.113406,5.197866,8.116096,...,1.0,2.142857,1.0,2.173913,1.0,17.0,10.0,23.0,27.0,23.0
std,0.050268,0.076981,2.347319,2.348233,3.174753,2.249651,1.933595,2.634996,3.199443,2.074894,...,0.0,0.562757,0.0,0.383223,0.0,NaN,NaN,NaN,NaN,NaN
min,45.415455,-73.941467,0.000000,1.000000,0.000000,2.000000,2.000000,0.000000,0.000000,0.000000,...,1.0,2.000000,1.0,2.000000,1.0,17.0,10.0,23.0,27.0,23.0
25%,45.490587,-73.627521,6.000000,6.000000,3.000000,5.000000,5.000000,2.000000,3.000000,7.000000,...,1.0,2.000000,1.0,2.000000,1.0,17.0,10.0,23.0,27.0,23.0
50%,45.507492,-73.582910,9.000000,9.000000,5.000000,6.000000,6.000000,5.000000,5.000000,9.000000,...,1.0,2.000000,1.0,2.000000,1.0,17.0,10.0,23.0,27.0,23.0
75%,45.541417,-73.563048,10.000000,10.000000,10.000000,9.000000,8.000000,6.000000,8.000000,10.000000,...,1.0,2.000000,1.0,2.000000,1.0,17.0,10.0,23.0,27.0,23.0
max,45.701156,-73.482572,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,...,1.0,6.000000,1.0,3.000000,1.0,17.0,10.0,23.0,27.0,23.0

# data cleaning

In [70]:
data.title.value_counts()

Condo for sale                3485
House for sale                1039
Duplex for sale                408
Triplex for sale               304
Quadruplex for sale            143
Condominium house for sale     110
Lot for sale                   109
Quintuplex for sale             73
Loft / Studio for sale          50
Land for sale                   11
Name: title, dtype: int64

### choose only condo

In [71]:
condo = data.loc[data.title == "Condo for sale", :]
condo.shape

(3485, 100)

In [72]:
#### these features might be very important
condo["Net area"].isnull().sum() 
condo["bedrooms"].isnull().sum()
condo["rooms"].isnull().sum()

21

In [73]:
condo.isnull().sum(axis=0) <= condo.shape[0]*0.1

title                  True
address                True
price                  True
lat                    True
long                   True
                      ...
< 15 years (%)        False
15 to 24 years (%)    False
25 to 44 years (%)    False
45 to 64 years (%)    False
> 65 years (%)        False
Length: 100, dtype: bool

In [74]:
# remove columns with more than 10% missing values
condo = condo.loc[:, (condo.isnull().sum(axis=0) <= condo.shape[0]*0.1)]
condo.head(5)

,title,address,price,lat,long,Restaurants,Shopping,Vibrant,Cycling friendly,Car friendly,...,College (%),Secondary (high) school (%),Apprentice or trade school diploma (%),No diploma (%),Non-immigrant population (%),Immigrant population (%),French (%),English (%),Others languages (%),walk_score
0,Condo for sale,"5050, Rue Bannantyne, apt. 203, Montréal (Verd...","$409,000",45.456079,-73.575949,7.0,8.0,5.0,9.0,6.0,...,16,18,9,14,75,25,64.0,22.0,14.0,NaN
1,Condo for sale,"201, Chemin de la Pointe-Sud, apt. 216, Montré...","$680,000",45.449347,-73.553327,3.0,3.0,1.0,7.0,10.0,...,16,18,9,14,75,25,64.0,22.0,14.0,NaN
2,Condo for sale,"8800, Rue Verville, apt. 101, Montréal (Ahunts...","$283,000",45.536589,-73.646590,8.0,10.0,5.0,3.0,6.0,...,16,20,10,17,59,41,65.0,10.0,25.0,72.0
3,Condo for sale,"185, Rue du Séminaire, apt. 605, Montréal (Le ...","$339,000",45.490915,-73.560779,10.0,10.0,9.0,9.0,5.0,...,16,19,9,18,74,26,59.0,26.0,15.0,70.0
4,Condo for sale,"7075, Rue Bombardier, apt. 108, Montréal (Anjou)","$177,800",45.606186,-73.588353,6.0,7.0,3.0,4.0,9.0,...,17,23,14,20,66,34,76.0,8.0,16.0,53.0

In [75]:
condo.columns

Index(['title', 'address', 'price', 'lat', 'long', 'Restaurants', 'Shopping',
       'Vibrant', 'Cycling friendly', 'Car friendly', 'Historic', 'Quiet',
       'Elementary Schools', 'High Schools', 'Parks', 'Nightlife', 'Groceries',
       'Daycares', 'Pedestrian friendly', 'Cafes', 'Transit friendly',
       'Greenery', 'rooms', 'Condominium type', 'Year built',
       'Population 2016 ', 'Population variation between 2011 2016 ',
       'Population density ', 'Unemployment rate 2016 ',
       'Less than $50,000 (%)', 'Between $50,000 and $80,000 (%)',
       'Between $80,000 and $100,000 (%)', 'Between $100,000 and $150,000 (%)',
       'More than $150,000 (%)', '1-person households (%)',
       '2-person households (%)', '3-person households (%)',
       '4-person households (%)', '5-person or more households (%)',
       'Couples without children at home (%)',
       'Couples with children at home (%)', 'Single-parent families (%)',
       'Owners (%)', 'Renters (%)', 'Before 1960 (%)',
       'Between 1961 and 1980 (%)', 'Between 1981 and 1990 (%)',
       'Between 1991 and 2000 (%)', 'Between 2001 and 2010 (%)',
       'Between 2011 and 2016 (%)', 'Single-family homes (%)',
       'Semi-detached or row houses (%)',
       'Buildings with less than 5 floors (%)',
       'Buildings with 5 or more floors (%)', 'Mobile homes (%)',
       'University (%)', 'College (%)', 'Secondary (high) school (%)',
       'Apprentice or trade school diploma (%)', 'No diploma (%)',
       'Non-immigrant population (%)', 'Immigrant population (%)',
       'French (%)', 'English (%)', 'Others languages (%)', 'walk_score'],
      dtype='object')

In [76]:
# drop address
condo.drop(columns = ["title", "address"])

,price,lat,long,Restaurants,Shopping,Vibrant,Cycling friendly,Car friendly,Historic,Quiet,...,College (%),Secondary (high) school (%),Apprentice or trade school diploma (%),No diploma (%),Non-immigrant population (%),Immigrant population (%),French (%),English (%),Others languages (%),walk_score
0,"$409,000",45.456079,-73.575949,7.0,8.0,5.0,9.0,6.0,5.0,8.0,...,16,18,9,14,75,25,64.0,22.0,14.0,NaN
1,"$680,000",45.449347,-73.553327,3.0,3.0,1.0,7.0,10.0,0.0,10.0,...,16,18,9,14,75,25,64.0,22.0,14.0,NaN
2,"$283,000",45.536589,-73.646590,8.0,10.0,5.0,3.0,6.0,2.0,0.0,...,16,20,10,17,59,41,65.0,10.0,25.0,72.0
3,"$339,000",45.490915,-73.560779,10.0,10.0,9.0,9.0,5.0,6.0,7.0,...,16,19,9,18,74,26,59.0,26.0,15.0,70.0
4,"$177,800",45.606186,-73.588353,6.0,7.0,3.0,4.0,9.0,0.0,6.0,...,17,23,14,20,66,34,76.0,8.0,16.0,53.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5723,"$1,450,000",45.483519,-73.616499,9.0,9.0,5.0,2.0,9.0,5.0,1.0,...,16,19,6,12,50,50,33.0,39.0,28.0,44.0
5724,"$279,000",45.495407,-73.606735,10.0,10.0,5.0,8.0,9.0,4.0,4.0,...,16,19,6,12,50,50,33.0,39.0,28.0,52.0
5725,"$599,000",45.481674,-73.569046,10.0,10.0,7.0,10.0,7.0,6.0,5.0,...,16,19,9,18,74,26,59.0,26.0,15.0,78.0
5726,"$1,050,000",45.481674,-73.569046,10.0,10.0,7.0,10.0,7.0,6.0,5.0,...,16,19,9,18,74,26,59.0,26.0,15.0,78.0
5727,"$1,100,000",45.481674,-73.569046,10.0,10.0,7.0,10.0,7.0,6.0,5.0,...,16,19,9,18,74,26,59.0,26.0,15.0,78.0

In [77]:
# normalize coordinate
# Montreal lat = 45.7, long = -73.5673 (by google) 
# 45.703282, -73.476106  to 45.356596, -73.991630
lat_mtl_min = 45
lat_mtl_max = 46
long_mtl_min = -74
long_mtl_max = -73
condo.lat = condo.lat-lat_mtl_min
condo.long = condo.long-long_mtl_min

In [78]:
envir = ['Restaurants', 'Shopping', 'Vibrant', 'Cycling friendly', 'Car friendly','Historic', 'Quiet',
         'Elementary Schools', 'High Schools', 'Parks', 'Nightlife', 'Groceries', 
         'Daycares', 'Pedestrian friendly', 'Cafes', 'Transit friendly','Greenery',]
condo.loc[ :, envir] = condo.loc[ :, envir] /10

In [79]:
condo[envir] = condo[envir].fillna(0)
condo[envir].isnull().any()

Restaurants            False
Shopping               False
Vibrant                False
Cycling friendly       False
Car friendly           False
Historic               False
Quiet                  False
Elementary Schools     False
High Schools           False
Parks                  False
Nightlife              False
Groceries              False
Daycares               False
Pedestrian friendly    False
Cafes                  False
Transit friendly       False
Greenery               False
dtype: bool

In [80]:
# transform type to binary
condo["Condominium type"] = condo["Condominium type"] == "Divided"

In [81]:
condo["Condominium type"] = condo["Condominium type"].astype(int)
condo["Condominium type"].value_counts()

1    3166
0     319
Name: Condominium type, dtype: int64

In [82]:
# year build
condo.loc[(condo["Year built"]=="To be built, New") | (condo["Year built"]== "Under construction, New"), "Year built"] = "2020"
condo["Year built"] = condo["Year built"].str.extract("(\d\d\d\d)")

# impute unkown age to 1900
condo["Year built"] = condo["Year built"].fillna(1900)
condo[condo["Year built"].isnull()].index.tolist()

condo["Year built"] = condo["Year built"].astype(int)

In [83]:
condo["Year built"].describe()
condo["Year built"] = (condo["Year built"] - 1800)/(2020-1800)

In [84]:
condo["Year built"].describe()

count    3485.000000
mean        0.873852
std         0.171350
min         0.090909
25%         0.850000
50%         0.954545
75%         0.986364
max         1.000000
Name: Year built, dtype: float64

In [85]:
### rooms, impute nan to 2
condo.rooms = condo.rooms.fillna(2)

In [86]:
### other statistics
stats = ['Unemployment rate 2016 ',
       'Less than $50,000 (%)', 'Between $50,000 and $80,000 (%)',
       'Between $80,000 and $100,000 (%)', 'Between $100,000 and $150,000 (%)',
       'More than $150,000 (%)', '1-person households (%)',
       '2-person households (%)', '3-person households (%)',
       '4-person households (%)', '5-person or more households (%)',
       'Couples without children at home (%)',
       'Couples with children at home (%)', 'Single-parent families (%)',
       'Owners (%)', 'Renters (%)', 'Before 1960 (%)',
       'Between 1961 and 1980 (%)', 'Between 1981 and 1990 (%)',
       'Between 1991 and 2000 (%)', 'Between 2001 and 2010 (%)',
       'Between 2011 and 2016 (%)', 'Single-family homes (%)',
       'Semi-detached or row houses (%)',
       'Buildings with less than 5 floors (%)',
       'Buildings with 5 or more floors (%)', 'Mobile homes (%)',
       'University (%)', 'College (%)', 'Secondary (high) school (%)',
       'Apprentice or trade school diploma (%)', 'No diploma (%)',
       'Non-immigrant population (%)', 'Immigrant population (%)',
       'French (%)', 'English (%)', 'Others languages (%)', 'walk_score']
condo.loc[:,stats] = condo.loc[:,stats].fillna(0)
condo.loc[:,stats] = condo.loc[:,stats]/100

In [87]:
condo[stats].isnull().any()

Unemployment rate 2016                    False
Less than $50,000 (%)                     False
Between $50,000 and $80,000 (%)           False
Between $80,000 and $100,000 (%)          False
Between $100,000 and $150,000 (%)         False
More than $150,000 (%)                    False
1-person households (%)                   False
2-person households (%)                   False
3-person households (%)                   False
4-person households (%)                   False
5-person or more households (%)           False
Couples without children at home (%)      False
Couples with children at home (%)         False
Single-parent families (%)                False
Owners (%)                                False
Renters (%)                               False
Before 1960 (%)                           False
Between 1961 and 1980 (%)                 False
Between 1981 and 1990 (%)                 False
Between 1991 and 2000 (%)                 False
Between 2001 and 2010 (%)                 False
Between 2011 and 2016 (%)                 False
Single-family homes (%)                   False
Semi-detached or row houses (%)           False
Buildings with less than 5 floors (%)     False
Buildings with 5 or more floors (%)       False
Mobile homes (%)                          False
University (%)                            False
College (%)                               False
Secondary (high) school (%)               False
Apprentice or trade school diploma (%)    False
No diploma (%)                            False
Non-immigrant population (%)              False
Immigrant population (%)                  False
French (%)                                False
English (%)                               False
Others languages (%)                      False
walk_score                                False
dtype: bool

In [88]:
### population stats 
#'Population 2016 ', 
#'Population variation between 2011 2016 ',
#'Population density '
condo["Population 2016 "].describe()
popMax = condo["Population 2016 "].max()
popMin = condo["Population 2016 "].min()
condo["Population 2016 "] = (condo["Population 2016 "] - popMin)/(popMax-popMin)

In [89]:
condo["Population variation between 2011 2016 "].describe()
condo["Population variation between 2011 2016 "] = condo["Population variation between 2011 2016 "]/9

In [90]:
condo["Population density "].describe()
popDenMax = condo["Population density "].max()
popDenMin = condo["Population density "].min()
condo["Population density "] = (condo["Population density "] - popDenMin)/(popDenMax-popDenMin)

In [91]:
condo.describe()

,lat,long,Restaurants,Shopping,Vibrant,Cycling friendly,Car friendly,Historic,Quiet,Elementary Schools,...,College (%),Secondary (high) school (%),Apprentice or trade school diploma (%),No diploma (%),Non-immigrant population (%),Immigrant population (%),French (%),English (%),Others languages (%),walk_score
count,3485.000000,3485.000000,3485.000000,3485.000000,3485.000000,3485.000000,3485.000000,3485.000000,3485.000000,3485.000000,...,3485.000000,3485.000000,3485.000000,3485.000000,3485.000000,3485.000000,3485.000000,3485.000000,3485.000000,3485.000000
mean,0.510731,0.409856,0.855122,0.872884,0.705739,0.693257,0.618164,0.479311,0.426686,0.796643,...,0.156123,0.190537,0.082872,0.139725,0.660574,0.339426,0.580146,0.229113,0.190740,0.729894
std,0.042181,0.050178,0.206455,0.195638,0.300939,0.230591,0.196160,0.254837,0.310936,0.203338,...,0.010759,0.023684,0.033139,0.054574,0.092178,0.092178,0.133568,0.091729,0.070279,0.233927
min,0.417212,0.121030,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.130000,0.150000,0.030000,0.080000,0.450000,0.210000,0.300000,0.050000,0.100000,0.000000
25%,0.491792,0.391649,0.700000,0.800000,0.400000,0.500000,0.500000,0.300000,0.200000,0.700000,...,0.150000,0.180000,0.060000,0.090000,0.630000,0.260000,0.540000,0.220000,0.140000,0.590000
50%,0.500518,0.426300,1.000000,1.000000,0.800000,0.700000,0.600000,0.600000,0.400000,0.900000,...,0.160000,0.180000,0.060000,0.120000,0.630000,0.370000,0.540000,0.260000,0.200000,0.800000
75%,0.529415,0.439169,1.000000,1.000000,1.000000,0.900000,0.800000,0.700000,0.700000,0.900000,...,0.160000,0.200000,0.100000,0.180000,0.740000,0.370000,0.650000,0.260000,0.200000,0.930000
max,0.697714,0.511552,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,0.210000,0.260000,0.180000,0.310000,0.790000,0.550000,0.850000,0.450000,0.380000,0.990000

In [92]:
condo['price'] = condo['price'].replace('[\$\,\.]', '', regex=True).astype(int)
condo

,title,address,price,lat,long,Restaurants,Shopping,Vibrant,Cycling friendly,Car friendly,...,College (%),Secondary (high) school (%),Apprentice or trade school diploma (%),No diploma (%),Non-immigrant population (%),Immigrant population (%),French (%),English (%),Others languages (%),walk_score
0,Condo for sale,"5050, Rue Bannantyne, apt. 203, Montréal (Verd...",409000,0.456079,0.424051,0.7,0.8,0.5,0.9,0.6,...,0.16,0.18,0.09,0.14,0.75,0.25,0.64,0.22,0.14,0.00
1,Condo for sale,"201, Chemin de la Pointe-Sud, apt. 216, Montré...",680000,0.449347,0.446673,0.3,0.3,0.1,0.7,1.0,...,0.16,0.18,0.09,0.14,0.75,0.25,0.64,0.22,0.14,0.00
2,Condo for sale,"8800, Rue Verville, apt. 101, Montréal (Ahunts...",283000,0.536589,0.353410,0.8,1.0,0.5,0.3,0.6,...,0.16,0.20,0.10,0.17,0.59,0.41,0.65,0.10,0.25,0.72
3,Condo for sale,"185, Rue du Séminaire, apt. 605, Montréal (Le ...",339000,0.490915,0.439221,1.0,1.0,0.9,0.9,0.5,...,0.16,0.19,0.09,0.18,0.74,0.26,0.59,0.26,0.15,0.70
4,Condo for sale,"7075, Rue Bombardier, apt. 108, Montréal (Anjou)",177800,0.606186,0.411647,0.6,0.7,0.3,0.4,0.9,...,0.17,0.23,0.14,0.20,0.66,0.34,0.76,0.08,0.16,0.53
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5723,Condo for sale,"4850, Chemin de la Côte-Saint-Luc, apt. PH2, M...",1450000,0.483519,0.383501,0.9,0.9,0.5,0.2,0.9,...,0.16,0.19,0.06,0.12,0.50,0.50,0.33,0.39,0.28,0.44
5724,Condo for sale,"4500, Chemin de la Côte-des-Neiges, apt. 701, ...",279000,0.495407,0.393265,1.0,1.0,0.5,0.8,0.9,...,0.16,0.19,0.06,0.12,0.50,0.50,0.33,0.39,0.28,0.52
5725,Condo for sale,"2301, Rue Saint-Patrick, apt. B509, Montréal (...",599000,0.481674,0.430954,1.0,1.0,0.7,1.0,0.7,...,0.16,0.19,0.09,0.18,0.74,0.26,0.59,0.26,0.15,0.78
5726,Condo for sale,"2301, Rue Saint-Patrick, apt. B215, Montréal (...",1050000,0.481674,0.430954,1.0,1.0,0.7,1.0,0.7,...,0.16,0.19,0.09,0.18,0.74,0.26,0.59,0.26,0.15,0.78
5727,Condo for sale,"2365, Rue Saint-Patrick, apt. 602A, Montréal (...",1100000,0.481674,0.430954,1.0,1.0,0.7,1.0,0.7,...,0.16,0.19,0.09,0.18,0.74,0.26,0.59,0.26,0.15,0.78

In [93]:
condo = condo.drop(columns=["title", "address"])
condo

,price,lat,long,Restaurants,Shopping,Vibrant,Cycling friendly,Car friendly,Historic,Quiet,...,College (%),Secondary (high) school (%),Apprentice or trade school diploma (%),No diploma (%),Non-immigrant population (%),Immigrant population (%),French (%),English (%),Others languages (%),walk_score
0,409000,0.456079,0.424051,0.7,0.8,0.5,0.9,0.6,0.5,0.8,...,0.16,0.18,0.09,0.14,0.75,0.25,0.64,0.22,0.14,0.00
1,680000,0.449347,0.446673,0.3,0.3,0.1,0.7,1.0,0.0,1.0,...,0.16,0.18,0.09,0.14,0.75,0.25,0.64,0.22,0.14,0.00
2,283000,0.536589,0.353410,0.8,1.0,0.5,0.3,0.6,0.2,0.0,...,0.16,0.20,0.10,0.17,0.59,0.41,0.65,0.10,0.25,0.72
3,339000,0.490915,0.439221,1.0,1.0,0.9,0.9,0.5,0.6,0.7,...,0.16,0.19,0.09,0.18,0.74,0.26,0.59,0.26,0.15,0.70
4,177800,0.606186,0.411647,0.6,0.7,0.3,0.4,0.9,0.0,0.6,...,0.17,0.23,0.14,0.20,0.66,0.34,0.76,0.08,0.16,0.53
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5723,1450000,0.483519,0.383501,0.9,0.9,0.5,0.2,0.9,0.5,0.1,...,0.16,0.19,0.06,0.12,0.50,0.50,0.33,0.39,0.28,0.44
5724,279000,0.495407,0.393265,1.0,1.0,0.5,0.8,0.9,0.4,0.4,...,0.16,0.19,0.06,0.12,0.50,0.50,0.33,0.39,0.28,0.52
5725,599000,0.481674,0.430954,1.0,1.0,0.7,1.0,0.7,0.6,0.5,...,0.16,0.19,0.09,0.18,0.74,0.26,0.59,0.26,0.15,0.78
5726,1050000,0.481674,0.430954,1.0,1.0,0.7,1.0,0.7,0.6,0.5,...,0.16,0.19,0.09,0.18,0.74,0.26,0.59,0.26,0.15,0.78
5727,1100000,0.481674,0.430954,1.0,1.0,0.7,1.0,0.7,0.6,0.5,...,0.16,0.19,0.09,0.18,0.74,0.26,0.59,0.26,0.15,0.78

In [94]:
condo = condo.loc[condo['price']<2000000,:]

# Machine Learning

In [95]:
y = condo.loc[:, "price"]
y.max()

1999000

In [96]:
y = condo.loc[:, "price"]
y = (y-y.min())/(y.max()-y.min())

X = condo.drop(columns=["price"])

In [97]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Linear Regression for price

In [98]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(X_train, y_train)
reg.score(X_train, y_train)

0.4040542056414521

In [99]:
y_pred_linear = reg.predict(X_test)
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, y_pred_linear)

0.014654151402744326

In [100]:
from sklearn.linear_model import LassoCV
from sklearn.datasets import make_regression

lassoCV = LassoCV(cv=10, random_state=0).fit(X_train, y_train)
lassoCV.score(X_train, y_train) 
y_pred_lassoCV = lassoCV.predict(X_test)
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, y_pred_lassoCV)

0.015059584828163908

# Pytorch for price

In [101]:
# !pip3 install torch
# !pip3 install matplotlib
# !pip3 install imageio
# !pip3 install sklearn

In [102]:
import torch
print(torch.__version__)
### pytorch 1.60 will have error while transfer model or tensor to gpu
### RuntimeError: CUDA error: an illegal memory access was encountered

from torch.autograd import Variable
import torch.nn.functional as F
import torch.utils.data as Data
import torch.nn as nn
import torch.optim as optim
from sklearn.preprocessing import StandardScaler 
from torch.utils.data import Dataset, DataLoader

import matplotlib.pyplot as plt
%matplotlib inline

import numpy as np
import imageio
import sklearn

torch.manual_seed(42)    # reproducible

1.4.0+cu100

In [103]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [104]:
EPOCHS = 200
BATCH_SIZE = 64

In [107]:
y_train = torch.from_numpy(np.array(y_train).astype(np.float32))
torch.FloatTensor(y_train)

tensor([0.2284, 0.2284, 0.5370,  ..., 0.1615, 0.1615, 0.8719])

In [108]:
## train data
class trainData(Dataset):
    
    def __init__(self, X_data, y_data):
        self.X_data = X_data
        self.y_data = y_data
        
    def __getitem__(self, index):
        return self.X_data[index], self.y_data[index]
        
    def __len__ (self):
        return len(self.X_data)


train_data = trainData(torch.FloatTensor(X_train), torch.FloatTensor(y_train))


## test data    
class testData(Dataset):
    
    def __init__(self, X_data):
        self.X_data = X_data
        
    def __getitem__(self, index):
        return self.X_data[index]
        
    def __len__ (self):
        return len(self.X_data)
    

test_data = testData(torch.FloatTensor(X_test))

In [109]:
train_loader = DataLoader(dataset=train_data, batch_size=BATCH_SIZE, shuffle=True)
test_loader = DataLoader(dataset=test_data, batch_size=1)

In [110]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(device)

cuda:0

In [111]:
# torch.cuda.current_device()
# torch.cuda.device(0)
# torch.cuda.device_count()
# torch.cuda.get_device_name(0)
# torch.cuda.is_available()

# print(torch.cuda.get_device_name(0))
# print('Memory Usage:')
# print('Allocated:', round(torch.cuda.memory_allocated(0)/10243,1), 'GB')
# print('Cached: ', round(torch.cuda.memory_cached(0)/10243,1), 'GB')

True

In [113]:
CUDA_LAUNCH_BLOCKING=1

In [115]:
import torch 
print(torch.__version__) ## Bug? when send data to cuda, torch 1.6 will return error

1.4.0+cu100

In [116]:
# ## test if gpu can be used
# mytensor = torch.Tensor([[1,2,3,4,5]])
# mytensor.numpy()
# torch.cuda.set_device(0)
# mytensor = torch.Tensor([[1,2,3,4,5]]).cuda()

In [121]:
# define a network
net = torch.nn.Sequential(
        torch.nn.Linear(63, 200),
        torch.nn.LeakyReLU(),
        torch.nn.Linear(200, 100),
        torch.nn.LeakyReLU(),
        torch.nn.Linear(100, 1),
    )
net.to(device)

Sequential(
  (0): Linear(in_features=63, out_features=200, bias=True)
  (1): LeakyReLU(negative_slope=0.01)
  (2): Linear(in_features=200, out_features=100, bias=True)
  (3): LeakyReLU(negative_slope=0.01)
  (4): Linear(in_features=100, out_features=1, bias=True)
)

In [122]:
optimizer = torch.optim.Adam(net.parameters(), lr=0.001)
loss_func = torch.nn.MSELoss()  # this is for regression mean squared loss

In [130]:
net.train()
for e in range(1, EPOCHS+1):
    epoch_loss = 0
    epoch_acc = 0
    for X_batch, y_batch in train_loader:
        X_batch, y_batch = X_batch.to(device), y_batch.to(device)
        optimizer.zero_grad()
        
        y_pred = net(X_batch)
        
        loss = loss_func(y_pred, y_batch.unsqueeze(1))
        
        loss.backward()
        optimizer.step()
        
        epoch_loss += loss.item()
        

    print(f'Epoch {e+0:03}: | Loss: {epoch_loss/len(train_loader):.5f}')

Epoch 001: | Loss: 0.01995
Epoch 002: | Loss: 0.01276
Epoch 003: | Loss: 0.01212
Epoch 004: | Loss: 0.01182
Epoch 005: | Loss: 0.01170
Epoch 006: | Loss: 0.01144
Epoch 007: | Loss: 0.01123
Epoch 008: | Loss: 0.01092
Epoch 009: | Loss: 0.01081
Epoch 010: | Loss: 0.01013
Epoch 011: | Loss: 0.01059
Epoch 012: | Loss: 0.01022
Epoch 013: | Loss: 0.01011
Epoch 014: | Loss: 0.00972
Epoch 015: | Loss: 0.01002
Epoch 016: | Loss: 0.00916
Epoch 017: | Loss: 0.00942
Epoch 018: | Loss: 0.00924
Epoch 019: | Loss: 0.00970
Epoch 020: | Loss: 0.00891
Epoch 021: | Loss: 0.00938
Epoch 022: | Loss: 0.00922
Epoch 023: | Loss: 0.00900
Epoch 024: | Loss: 0.00877
Epoch 025: | Loss: 0.00822
Epoch 026: | Loss: 0.00834
Epoch 027: | Loss: 0.00813
Epoch 028: | Loss: 0.00820
Epoch 029: | Loss: 0.00823
Epoch 030: | Loss: 0.00806
Epoch 031: | Loss: 0.00799
Epoch 032: | Loss: 0.00775
Epoch 033: | Loss: 0.00814
Epoch 034: | Loss: 0.00774
Epoch 035: | Loss: 0.00788
Epoch 036: | Loss: 0.00735
Epoch 037: | Loss: 0.00772
Epoch 038: | Loss: 0.00763
Epoch 039: | Loss: 0.00698
Epoch 040: | Loss: 0.00738
Epoch 041: | Loss: 0.00741
Epoch 042: | Loss: 0.00742
Epoch 043: | Loss: 0.00712
Epoch 044: | Loss: 0.00739
Epoch 045: | Loss: 0.00690
Epoch 046: | Loss: 0.00663
Epoch 047: | Loss: 0.00687
Epoch 048: | Loss: 0.00696
Epoch 049: | Loss: 0.00671
Epoch 050: | Loss: 0.00664
Epoch 051: | Loss: 0.00637
Epoch 052: | Loss: 0.00622
Epoch 053: | Loss: 0.00670
Epoch 054: | Loss: 0.00652
Epoch 055: | Loss: 0.00652
Epoch 056: | Loss: 0.00707
Epoch 057: | Loss: 0.00656
Epoch 058: | Loss: 0.00624
Epoch 059: | Loss: 0.00618
Epoch 060: | Loss: 0.00616
Epoch 061: | Loss: 0.00634
Epoch 062: | Loss: 0.00639
Epoch 063: | Loss: 0.00620
Epoch 064: | Loss: 0.00656
Epoch 065: | Loss: 0.00679
Epoch 066: | Loss: 0.00630
Epoch 067: | Loss: 0.00615
Epoch 068: | Loss: 0.00587
Epoch 069: | Loss: 0.00573
Epoch 070: | Loss: 0.00615
Epoch 071: | Loss: 0.00616
Epoch 072: | Loss: 0.00583
Epoch 073: | Loss: 0.00588
Epoch 074: | Loss: 0.00589
Epoch 075: | Loss: 0.00562
Epoch 076: | Loss: 0.00608
Epoch 077: | Loss: 0.00596
Epoch 078: | Loss: 0.00574
Epoch 079: | Loss: 0.00563
Epoch 080: | Loss: 0.00555
Epoch 081: | Loss: 0.00553
Epoch 082: | Loss: 0.00558
Epoch 083: | Loss: 0.00552
Epoch 084: | Loss: 0.00520
Epoch 085: | Loss: 0.00531
Epoch 086: | Loss: 0.00518
Epoch 087: | Loss: 0.00516
Epoch 088: | Loss: 0.00517
Epoch 089: | Loss: 0.00563
Epoch 090: | Loss: 0.00562
Epoch 091: | Loss: 0.00541
Epoch 092: | Loss: 0.00539
Epoch 093: | Loss: 0.00533
Epoch 094: | Loss: 0.00516
Epoch 095: | Loss: 0.00497
Epoch 096: | Loss: 0.00543
Epoch 097: | Loss: 0.00590
Epoch 098: | Loss: 0.00526
Epoch 099: | Loss: 0.00492
Epoch 100: | Loss: 0.00503
Epoch 101: | Loss: 0.00497
Epoch 102: | Loss: 0.00483
Epoch 103: | Loss: 0.00512
Epoch 104: | Loss: 0.00511
Epoch 105: | Loss: 0.00497
Epoch 106: | Loss: 0.00480
Epoch 107: | Loss: 0.00498
Epoch 108: | Loss: 0.00507
Epoch 109: | Loss: 0.00508
Epoch 110: | Loss: 0.00501
Epoch 111: | Loss: 0.00479
Epoch 112: | Loss: 0.00495
Epoch 113: | Loss: 0.00504
Epoch 114: | Loss: 0.00552
Epoch 115: | Loss: 0.00525
Epoch 116: | Loss: 0.00509
Epoch 117: | Loss: 0.00499
Epoch 118: | Loss: 0.00458
Epoch 119: | Loss: 0.00486
Epoch 120: | Loss: 0.00540
Epoch 121: | Loss: 0.00583
Epoch 122: | Loss: 0.00466
Epoch 123: | Loss: 0.00469
Epoch 124: | Loss: 0.00490
Epoch 125: | Loss: 0.00498
Epoch 126: | Loss: 0.00485
Epoch 127: | Loss: 0.00449
Epoch 128: | Loss: 0.00449
Epoch 129: | Loss: 0.00438
Epoch 130: | Loss: 0.00461
Epoch 131: | Loss: 0.00450
Epoch 132: | Loss: 0.00478
Epoch 133: | Loss: 0.00449
Epoch 134: | Loss: 0.00443
Epoch 135: | Loss: 0.00510
Epoch 136: | Loss: 0.00486
Epoch 137: | Loss: 0.00422
Epoch 138: | Loss: 0.00460
Epoch 139: | Loss: 0.00489
Epoch 140: | Loss: 0.00451
Epoch 141: | Loss: 0.00422
Epoch 142: | Loss: 0.00443
Epoch 143: | Loss: 0.00465
Epoch 144: | Loss: 0.00449
Epoch 145: | Loss: 0.00443
Epoch 146: | Loss: 0.00468
Epoch 147: | Loss: 0.00501
Epoch 148: | Loss: 0.00467
Epoch 149: | Loss: 0.00452
Epoch 150: | Loss: 0.00452
Epoch 151: | Loss: 0.00427
Epoch 152: | Loss: 0.00438
Epoch 153: | Loss: 0.00432
Epoch 154: | Loss: 0.00416
Epoch 155: | Loss: 0.00434
Epoch 156: | Loss: 0.00424
Epoch 157: | Loss: 0.00416
Epoch 158: | Loss: 0.00433
Epoch 159: | Loss: 0.00454
Epoch 160: | Loss: 0.00461
Epoch 161: | Loss: 0.00461
Epoch 162: | Loss: 0.00428
Epoch 163: | Loss: 0.00411
Epoch 164: | Loss: 0.00409
Epoch 165: | Loss: 0.00433
Epoch 166: | Loss: 0.00411
Epoch 167: | Loss: 0.00414
Epoch 168: | Loss: 0.00393
Epoch 169: | Loss: 0.00419
Epoch 170: | Loss: 0.00400
Epoch 171: | Loss: 0.00395
Epoch 172: | Loss: 0.00444
Epoch 173: | Loss: 0.00418
Epoch 174: | Loss: 0.00394
Epoch 175: | Loss: 0.00407
Epoch 176: | Loss: 0.00402
Epoch 177: | Loss: 0.00400
Epoch 178: | Loss: 0.00418
Epoch 179: | Loss: 0.00398
Epoch 180: | Loss: 0.00384
Epoch 181: | Loss: 0.00403
Epoch 182: | Loss: 0.00417
Epoch 183: | Loss: 0.00416
Epoch 184: | Loss: 0.00389
Epoch 185: | Loss: 0.00401
Epoch 186: | Loss: 0.00420
Epoch 187: | Loss: 0.00397
Epoch 188: | Loss: 0.00437
Epoch 189: | Loss: 0.00471
Epoch 190: | Loss: 0.00460
Epoch 191: | Loss: 0.00428
Epoch 192: | Loss: 0.00454
Epoch 193: | Loss: 0.00459
Epoch 194: | Loss: 0.00433
Epoch 195: | Loss: 0.00401
Epoch 196: | Loss: 0.00379
Epoch 197: | Loss: 0.00404
Epoch 198: | Loss: 0.00407
Epoch 199: | Loss: 0.00399
Epoch 200: | Loss: 0.00391

In [131]:
y_pred_list = []

net.eval()
with torch.no_grad():
    for X_batch in test_loader:
        X_batch = X_batch.to(device)
        y_test_pred = net(X_batch)
#         print(y_test_pred)

        y_pred_list.append(y_test_pred.cpu().numpy())
        
y_pred_list = [a.squeeze().tolist() for a in y_pred_list]

In [132]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, y_pred_list)

0.013642792069683